openapi: 3.0.0
info:
  title: Dubai's Landmarks
  version: 1.0.0
  description: APIs for Dubai's Landmarks blog
servers:
  - url: /api/

paths:

  /users/signup:
    post:
      tags:
        - User
      description: User Sign Up
      requestBody:
        content:
            application/json:
              schema:
                properties:
                  username:
                    required: true
                    type: string
                    description: User Username
                  password:
                    required: true
                    type: string
                    description: User password
                  email:
                    required: false
                    type: string
                    description: User email
      responses:
        200:
          description: User Successfully Sign Up
          content:
            application/json:
              schema:
                propeties:
                  message:
                    type: string
                    description: success message
        400:
          description: User failed to Sign Up
          content:
            application/json:
              schema:
                propeties:
                  errorMessage:
                    type: string
                    description: error message
  /users/logout:
    get:
      tags:
          - User
      description: Log Out user
      responses:
        200:
          description: User Successfully Log Out
          content:
            application/json:
              schema:
                propeties:
                  message:
                    type: string
                    description: success message
  /users/login:
    post:
      tags:
        - User
      description: Log In user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  description: User Username
                password:
                  type: string
                  description: User password
      responses:
        200:
          description: User Successfully Log In
          content:
            application/json:
              schema:
                propeties:
                  objectId:
                    type: string
                    description: User Id
                  username:
                    type: string
                    description: User Username
                  email:
                    type: string
                    description: User Email;
                  sessionToke:
                    type: string
                    description: User session Token
        400:
          description: User unable to Log In
          content:
            application/json:
              schema:
                propeties:
                  message:
                    type: string
                    description: error message
  
  /attractions:
    get:
      tags:
          - Attractions
      description: get all attractions
      responses:
        200:
          description: Get Successfully all the attractions orgered by 'order' field
          content:
            application/json:
              schema:
                type: array
                description: Array of attractions
                  items:
                    type: object
                    $ref: '#components/schemas/Atractions'
    put:
      tags:
          - Attractions
      description: Update attraction
      requestBody:
        content:
          application/json:
            schema:
            type: object
              properties:
                url:
                  required: false
                  type: string
                  description: Attraction Url
                title:
                  required: false
                  type: string
                  description: Attraction Title
                short_info:
                  required: false
                  type: string
                  description: Attraction Short Info
                description:
                  required: false
                  type: string
                  description: Attraction Description
                location:
                  required: false
                  type: array
                  description: Attraction Location cordinates
                    items:
                      type: number
                photo:
                  required: false
                  type: string
                  description: Attraction Photo in base64
      responses:
        200:
          description: Upadate Successfully the attraction
          content:
            application/json:
               schema:
                propeties:
                  message:
                    type: string
                    description: success message
        401:
          description: User is not authorized
          content:
            application/json:
               schema:
                propeties:
                  message:
                    type: string
                    description: Unauthorized User
        400:
          description: Unable to update attraction
          content:
            application/json:
               schema:
                propeties:
                  message:
                    type: string
                    description: fail to update attraction
  /attractions/{id}:
    get:
      tags:
        - Attractions
      description: get Attraction by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of an Attraction
      responses:
        200:  
          description: Upadate Successfully the attraction
          content:
            application/json:
               schema:
                propeties:
                  $ref: '#components/schemas/Atractions'
        400:
          description: Unable to get attraction
          content:
            application/json:
               schema:
                propeties:
                  message:
                    type: string
                    description: fail to get attraction

components:
  schemas:

    Attraction:
      properties: 
        url:
          type: string
          description: Attraction Url
        title:
          type: string
          description: Attraction Title
        short_info:
          type: string
          description: Attraction Short Info
        description:
          type: string
          description: Attraction Description
        location:
          type: array
          description: Attraction Location cordinates
            items:
              type: string
        order:
          type: number
          description: Attraction Order
        photo:
          type: object
          description: Attraction Photo
          properties:
            __type:
              type: string
              description: type File
            name: 
              type: string
              description: Name of photo
            url:
              type: string
              description: Url of Photo
        createdAt:
          type: object
          format: data-time
          description: Attraction Inserted Date
        updatedAt:
          type: object
          format: data-time
          description: Attraction Modified Date